fouedrecaptcha_homepage:
    path:     /
    defaults: { _controller: FouedrecaptchaBundle:Default:index }
form_submit:
    path:     /handler
    defaults: { _controller: FouedrecaptchaBundle:Default:handler }
